#!/usr/bin/env python3
"""Generate an AI-reviewer-ready package for the latest market report.

Output: data/review_package_{report_type}_{YYYYMMDD_HHMMSS}.md

The package contains everything a reviewer AI needs:
  - Project context
  - Ground-truth market snapshot
  - Automated validation results (structure + price)
  - The full report text
  - A scoring rubric with expected output format
"""

import json
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

TPE = timezone(timedelta(hours=8))

REPORT_TYPE_NAMES = {
    "tw_open":  "台股開盤戰報",
    "us_close": "美股收盤日報",
    "tw_close": "台股收盤日報",
    "us_open":  "美股開盤日報",
}

# ── Section counts per report (for summary) ───────────────────────────────────

SECTION_COUNTS = {
    "tw_open":  "§1–§15 + Tomorrow Key Signals / Risk Matrix / Rotation Assessment / AI Trend Health Check",
    "tw_close": "§1–§15 + Tomorrow Key Signals / Risk Matrix / Rotation Assessment / AI Trend Health Check",
    "us_open":  "§1–§15 + Tomorrow Key Signals / Risk Matrix / Rotation Assessment / AI Trend Health Check",
    "us_close": "§1–§22 + Tomorrow Key Signals / Risk Matrix / Rotation Assessment / AI Trend Health Check",
}

# ── Helpers ────────────────────────────────────────────────────────────────────

def _latest_report(report_type: str) -> tuple[Path | None, str]:
    reports_dir = Path(__file__).parent.parent / "reports"
    files = sorted(reports_dir.glob(f"{report_type}_*.md"), reverse=True)
    if not files:
        return None, ""
    return files[0], files[0].read_text(encoding="utf-8")


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}


# ── Section builders ───────────────────────────────────────────────────────────

def _section_project_context(report_type: str) -> str:
    name = REPORT_TYPE_NAMES.get(report_type, report_type)
    sections_desc = SECTION_COUNTS.get(report_type, "N/A")
    return f"""## PART 1 — PROJECT CONTEXT

You are reviewing an **institutional-grade automated market report** generated by a GitHub Actions pipeline.

### System Overview
- **Report type**: `{report_type}` — {name}
- **Generator**: Google Gemini API (`gemini-2.0-flash`) + Google Search grounding
- **Distribution**: Telegram + Email
- **Language**: Traditional Chinese (繁體中文)

### Required Report Structure
Every `{report_type}` report must contain: {sections_desc}

### Hard Rules (violations are always errors)
1. **No price estimation** — prices MUST come from live web search or the injected market snapshot.
   If search fails, the field must say `⚠️ 未取得`, not an estimated value.
2. **No arithmetic from known prices** — e.g., `cost_basis × 1.01` is forbidden.
3. **No filler phrases** — "市場情緒樂觀", "投資者信心增強" etc. are banned.
4. **Driver / Risk / Signal structure** — every analytical conclusion should include a driver,
   a risk condition, and a confirmation signal.
5. **No URL citations** — this is a Telegram/Email report, not a research paper.
6. **Snapshot prices are final** — if the prompt header contained a "系統提供的市場快照",
   those numbers are ground truth and must appear verbatim in the report.

### Quality Standard
Institutional grade: answers WHY the market moved, not just WHAT happened.
Each section must have enough data density that a trader can make a decision from it.
"""


def _section_snapshot(snapshot: dict) -> str:
    if not snapshot:
        return "## PART 2 — MARKET SNAPSHOT (GROUND TRUTH)\n\n*No snapshot available for this run.*\n"

    fetched_at = snapshot.get("generated_at", "")[:19].replace("T", " ")
    lines = [
        "## PART 2 — MARKET SNAPSHOT (GROUND TRUTH)",
        "",
        f"Fetched via yfinance at **{fetched_at} TPE**.",
        "These are the verified closing prices. Use them to cross-check the report in Part 4.",
        "",
    ]

    tw = snapshot.get("tw_stocks", {})
    if tw:
        lines += ["**Taiwan Stocks (TWD)**",
                  "| Code | Name | Close | Change% |",
                  "|------|------|-------|---------|"]
        for code, d in tw.items():
            lines.append(f"| {code} | {d['name']} | {d['price']:,.1f} | {d['change_pct']:+.2f}% |")
        lines.append("")

    us = snapshot.get("us_markets", {})
    if us:
        lines += ["**US Markets / Indices**",
                  "| Symbol | Name | Latest | Change% |",
                  "|--------|------|--------|---------|"]
        for key, d in us.items():
            val = f"{d['price']:.2f}%" if d.get("currency") == "percent" else f"{d['price']:,.2f}"
            lines.append(f"| {key} | {d['name']} | {val} | {d['change_pct']:+.2f}% |")
        lines.append("")

    forex = snapshot.get("forex", {})
    if forex:
        lines.append("**Forex**")
        for key, d in forex.items():
            lines.append(f"- {d['name']}: {d['price']:.4f} ({d['change_pct']:+.2f}%)")
        lines.append("")

    return "\n".join(lines)


def _section_validation(results: dict) -> str:
    if not results:
        return "## PART 3 — AUTOMATED VALIDATION RESULTS\n\n*No validation results found.*\n"

    lines = ["## PART 3 — AUTOMATED VALIDATION RESULTS", ""]

    struct = results.get("structure")
    if struct:
        status = "⚠️ TRUNCATED" if struct.get("truncated") else "✓ complete"
        missing = struct.get("sections_missing", [])
        lines += [
            "### Structure Check",
            f"- Sections: {struct.get('sections_present')}/{struct.get('sections_total')} present — **{status}**",
            f"- Missing sections: {missing if missing else 'none'}",
            f"- `⚠️ 未取得` occurrences: {struct.get('missing_data_count', 0)} "
            f"(~{struct.get('missing_data_pct', 0)}% of fields)",
            f"- Report length: {struct.get('char_count', 0):,} characters",
            "",
        ]

    price = results.get("price_check")
    if price:
        passed  = price.get("passed",    [])
        failed  = price.get("failed",    [])
        unchecked = price.get("unchecked", [])
        lines += [
            "### Price Accuracy Check (5% tolerance vs market snapshot)",
            f"- ✓ Pass: {len(passed)}  ✗ Fail: {len(failed)}  ? Unchecked: {len(unchecked)}",
        ]
        if failed:
            lines.append("")
            lines.append("**Price deviations (>5%):**")
            lines.append("| Ticker | Reported | Actual | Diff% |")
            lines.append("|--------|----------|--------|-------|")
            for row in failed:
                lines.append(f"| {row['ticker']} | {row['reported']} | {row['actual']} | {row['diff_pct']}% |")
        lines.append("")

    return "\n".join(lines)


def _section_report(report_text: str, report_path: Path | None) -> str:
    fname = report_path.name if report_path else "unknown"
    return f"""## PART 4 — REPORT TO REVIEW

**File**: `{fname}`

---

{report_text}

---
"""


def _section_rubric() -> str:
    return """## PART 5 — REVIEW INSTRUCTIONS

Please review the report in Part 4 against the context in Parts 1–3.

### Scoring Rubric

| Category | Max Points | Criteria |
|----------|-----------|---------|
| Completeness | 20 | All required sections present, none truncated, no empty sections |
| Data Accuracy | 25 | Prices match Part 2 snapshot; no estimation markers; no ⚠️ 未取得 in critical fields |
| Analysis Depth | 25 | WHY not just WHAT; driver/risk/signal in conclusions; quantified claims |
| Rule Compliance | 20 | No filler phrases; no URL citations; no arithmetic estimation |
| Actionability | 10 | Bull/Bear setups are specific; trading plan has clear triggers |

### Critical Fields (Data Accuracy — always check these)
- Taiwan: TAIEX index close, 台積電(2330), 聯發科(2454), 廣達(2382), 鴻海(2317)
- US: S&P 500, NASDAQ, VIX, NVDA, SOX
- Macro: US10Y yield, DXY, USD/TWD

### Output Format (respond in JSON)
```json
{
  "overall_score": 0-100,
  "tier1_hard_failures": [
    {"section": "§N or section name", "issue": "description", "quote": "exact text from report"}
  ],
  "tier2_quality_issues": [
    {"section": "§N or section name", "issue": "description"}
  ],
  "tier3_suggestions": [
    {"section": "§N or section name", "suggestion": "how to improve"}
  ],
  "score_breakdown": {
    "completeness": 0-20,
    "data_accuracy": 0-25,
    "analysis_depth": 0-25,
    "rule_compliance": 0-20,
    "actionability": 0-10
  },
  "summary": "2-3 sentences summarising overall quality"
}
```

Focus on Tier 1 failures first. If there are hard failures, note them before discussing quality.
"""


# ── Entry point ────────────────────────────────────────────────────────────────

def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: prepare_review.py <report_type>", file=sys.stderr)
        sys.exit(1)

    report_type = sys.argv[1]
    data_dir = Path(__file__).parent.parent / "data"
    data_dir.mkdir(exist_ok=True)

    report_path, report_text = _latest_report(report_type)
    if not report_text:
        print(f"[review] no report found for {report_type} — skipping", file=sys.stderr)
        sys.exit(0)

    snapshot    = _load_json(data_dir / "market_snapshot.json")
    val_results = _load_json(data_dir / "validation_results.json")

    now_str = datetime.now(tz=TPE).strftime("%Y%m%d_%H%M%S")
    out_path = data_dir / f"review_package_{report_type}_{now_str}.md"

    name = REPORT_TYPE_NAMES.get(report_type, report_type)
    header = (
        f"# AI Review Package — {name}\n\n"
        f"> Generated: {datetime.now(tz=TPE).strftime('%Y-%m-%d %H:%M TPE')}  \n"
        f"> Report type: `{report_type}`  \n"
        f"> Report file: `{report_path.name if report_path else 'N/A'}`\n\n"
        "---\n\n"
    )

    body = "\n\n---\n\n".join([
        _section_project_context(report_type),
        _section_snapshot(snapshot),
        _section_validation(val_results),
        _section_report(report_text, report_path),
        _section_rubric(),
    ])

    out_path.write_text(header + body, encoding="utf-8")
    print(f"[review] package written → {out_path}  ({out_path.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
